apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ovejgrf5b-go
  janus-idp.io/tekton: ovejgrf5b-go
  backstage.io/kubernetes-id: ovejgrf5b-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ovejgrf5b-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
